language: java
dist: trusty
deploy:
  provider: script
  script: cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy
  skip_cleanup: true
  on:
    all_branches: true
env:
  global:
    - secure: nAaT6xZEXa7mcQpSip7gcWXLREFAO9Dh9aJMTV8FzFwYni22fN74QDm/bqG26rMX3DgPUPoe2p5+B7f3aKl/lGL9jSWiIo2descSwgwnN73Ac9EY1kuL0wqWcpuaDuTdz1C/DygqnMdhpiCPKoHOY53tkl4+QAGgJviC0Wtk9XYQG3ulA+vuL0htqdU2m/O2QnIovKSCD+6fL88/HBHeQ8liTOOp5GdMcq9tuCPka6Q6JFb36+PfJQL3EJ1Knw6e1sPRKnt4Cj7r6ko7Lq860YkRW+3bjm2TAj5RXDn9h30UwQjOm/o/HqibICyDfsA1JtjWvwHgNcVgV2iZMIdsM0/YdAA/vXlkfxdf14yTOlY4Dy4hGAx6hBD8IiKSI54aAtwkbWnwtgPHBiUqx/BkFMHBdpsK2Zg6P9ldNJhnpQmVUla21fOhaDT6uA5Vi/z51pF7os6i6dJgfmMKlCAPRoyx2oY3n+BKXQcQZ3Mz8MTTGEOfox0gVXKg7I/p8uNwETjlhacKGYut5boy7ujt641+Yx6w+iTLrVNcDFgedMaZC5J8vT72DU9pOojMG7atR/81sBxB48YcFz1FnZjmjkMW+0iVDaO+ClNY/BBOiGWi3AfqFukmQngjudVyBSZERFUY/8m+3x5ylu90qF1JLhmBFThWSiCQ0Kd+YrGb/Es=
notifications:
  slack:
    rooms:
      secure: 3PJK04S1l7cYtQGVStBBuAwXd2d+M3gem5lrO4jInAZOnaX+DesvhN3a89ggDFgGtnhYvlXpLdYKhSGFYT12kIpISeA5R6Bo2PfV/mushRep0JCMcXHmD3qvkb7zK29xUR7Rt1PvFOaBoYj/1HSA7Xm/ISGtzWB4AB2CzhpUtdvR9yaJaJl0Njuu230K3nz32msHK/TPhgZ+C2OS2q11kWrpOWCBpHqaGToQnkAjF5AeIlK+tEboiR4DtdnQ2OzX9Swod3VYOEp26v0lqU712vqhVG6e9b1pLR8p6sXdiU2BsI871V8cUhayjomojCQgOWgr4AxpfksdKGdIZKXeimwAZhy1301oO3MR5vxBt7wleJgVSUf1y3+nNQyyr9USSlv2KDftXltH99RGfv5NWtV6zvWebdXUTZJqMIQezhrhwub+d9It+qtbeiRRvSe1BkZE3xKiKGmjZCK2z9i6kheJQW/RF/mXGT4xfzMlJIJW0azbF+36gBELcswBO0VKDfH6EJgoTaz70W1La9LofmPLzhXf8kmJQ0jZwzd0FhJykFrsNYwLl4EFedw8YKed7CCEz9WhQECimdlanzs/euJWJDOuFfZc/L0HvQvw4Iq4R0zSL4kW+mYTYp2la9j8i+xzgDvu/MflCKg7+60nnD9QuDsOzEg1KelUZLRXjpc=