version: "3.7"

services:
  agent:
    build: .
    user: root
    privileged: true
    ports:
      - 127.0.0.1:5080:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/rootfs:ro
    environment:
      - NUVLABOX_UUID=${NUVLABOX_UUID}
      - NUVLA_ENDPOINT=${NUVLA_ENDPOINT:-nuvla.io}
      - NUVLA_ENDPOINT_INSECURE=False
    labels:
      - nuvlabox.component=True
      - nuvlabox.deployment=production
