version: "3.7"

services:
  agent:
    build: .
    user: root
    expose:
      - 5000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NUVLABOX_ID=<placeholder>
      - NUVLA_ENDPOINT=https://nuv.la
    labels:
      - nuvlabox.component=True




