version: "3.7"

services:
  agent:
    build: .
    user: root
    expose:
      - 5000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NUVLABOX_UUID=${NUVLABOX_UUID}
      - NUVLA_ENDPOINT=${NUVLA_ENDPOINT:-nuvla.io}
      - NUVLA_ENDPOINT_INSECURE=False
    labels:
      - nuvlabox.component=True
      - nuvlabox.deployment=production
